#%RAML 1.0
title: Loan Management System

types:
  Loan:
    type: object
    discriminator: loan_id
    properties:
      loan_id: number
      amount: number
      term: number
      rate: number
      installment: number
      date: datetime
    example:
      loan_id: 1
      amount: 1000
      term: 12
      rate: 0.05
      installment: 85.60
      date: "2019-05-09T03:18:00Z"
  Payment:
    type: object
    discriminator: payment_id
    properties:
      payment_id: number
      loan_id: number
      payment: string
      date: datetime
      amount: number
    example:
      payment_id: 1
      loan_id: 1
      payment: "made"
      date: "2019-05-10T04:18:00Z"
      amount: 85.60
/loans:
  post:
    description: Create a loan application. Loans are automatically accepted.
    body:
      application/json:
        properties:
          amount:
            displayName: Loan Amount
            type: number
            format: float
            description: Loan amount in dollars
            example: 1000
            required: true
          term:
            displayName: Loan Term
            type: number
            format: int
            description: Number of months that will take until the loan gets paid-off
            example: 12
            required: true
          rate:
            displayName: Interest Rate
            type: number
            format: float
            description: Interest rate as decimal
            example: 0.05
            required: true
          date:
            displayName: Date of Loan
            type: datetime
            description: When the loan was requested (origination date as an ISO 8601 string)
            example: "2019-05-09T03:18:00Z"
            required: true
        example:
          amount: 1000
          term: 12
          rate: 0.05
          date: "2019-05-09T03:18:00Z"
    responses:
      201:
        body:
          application/json:
            example:
              loan_id: 1
              installment: 85.60
  get:
    description: Retrieve all the loan applications.
    responses:
      200:
        body:
          application/json:
            example:
              loan_id: 1
              amount: 1000
              term: 12
              rate: 0.05
              date: "2019-05-09T03:18:00Z"
              installment: 85.6
  /{id}/payments:
    post:
      description: Create a record of a payment made or missed.
      body:
        application/json:
          properties:
            payment:
              displayName: Payment Status
              type: string
              description: Type of payment (made or missed)
              example: "made"
              required: true
            date:
              displayName: Date of Payment
              type: datetime
              description: Payment date
              example: "2019-05-10T04:18:00Z"
              required: true
            amount:
              displayName: Amount of Payment
              type: number
              format: float
              description: Amount of payment made or missed in dollars
              example: 85.60
              required: true
          example:
            payment: "made"
            date: "2019-05-10T04:18:00Z"
            amount: 85.60
      responses: 
        201:
          body:
            application/json:
              example:
                payment_id: 1
                loan_id: 1
                payment: "made"
                date: "2019-05-07T04:18:00Z"
                amount: 85.60
    get:
      description: Retrieve all the payments for an specific loan.
      responses:
        200:
          body:
            application/json:
              example:
                loan_id: 1
                payment_id: 1
                payment: "made"
                date: "2019-05-07T04:18:00Z"
                amount: 85.60
  /{id}/balance:
    post:
      description: Get the volume of outstanding debt (i.e. debt yet to be paid) at some point in time.
      body:
        application/json:
          properties:
            date:
              displayName: Date of Outstanding Debt
              type: datetime
              description: Loan balance until this date
              example: "2019-06-04T12:30:00Z"
          example:
            date: "2019-06-04T12:30:00Z"
      responses:
        200:
          body:
            application/json:
              example:
                balance: 40