# Generated by Django 2.2.1 on 2019-05-19 16:53

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[core.validators.validate_amount]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment',
            field=models.CharField(max_length=6, validators=[core.validators.validate_payment]),
        ),
    ]
