# Generated by Django 2.2.1 on 2019-05-17 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190516_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
