# Generated by Django 2.2.1 on 2019-05-16 20:24

import core.validators
from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190516_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=10, validators=[djmoney.models.validators.MinMoneyValidator(1)]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='term',
            field=models.IntegerField(validators=[core.validators.validate_term]),
        ),
    ]
