# Generated by Django 2.2.1 on 2019-05-19 17:05

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190519_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(validators=[core.validators.validate_date]),
        ),
    ]
