# Generated by Django 2.2.1 on 2019-05-19 22:20

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190518_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[core.validators.validate_amount]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(validators=[core.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment',
            field=models.CharField(max_length=6, validators=[core.validators.validate_payment]),
        ),
    ]
