# Generated by Django 2.2.1 on 2019-05-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190519_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
